// Changes summary:
// - Each answer row in the PDF now shows field.officialFieldName as a small muted
//   reference line below the field label when available (e.g. "SS-4 Line 1: Legal name").
//   This lets the user trace each answer back to the real government form field.
// - All other PDF layout and content unchanged.

import type { FormTemplate } from './formTemplates';
import {
  PDF_COLORS, setFill, setColor, setStroke,
  renderPageHeader, textBlock, addPageNumbers,
} from './pdf';

export interface CompletedFormEntry {
  template: FormTemplate;
  formData: Record<string, string>;
}

/**
 * Generates a multi-section compliance packet PDF containing every form filled
 * during a "Complete All Required Forms" session.
 *
 * Sections: Cover page → one section per form → submission checklist
 */
export async function generateCompliancePacket(
  forms: CompletedFormEntry[],
  location: string,
): Promise<void> {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'letter' });

  const margin   = 18;
  const pageW    = doc.internal.pageSize.getWidth();
  const contentW = pageW - margin * 2;

  const brand = 'RegBot — Compliance Packet';

  // Per-section page header — title goes in the second stripe row
  const header = (title: string, subtitle?: string) =>
    renderPageHeader(doc, pageW, margin, brand, location, title, subtitle);

  // Page-break callback: add page, re-render header, return new y
  const newPage = (title = '(continued)') => {
    doc.addPage();
    header(title);
    return 28;
  };

  // Shorthand text-block using this packet's context
  const tb = (text: string, x: number, y: number, maxW: number, lineH?: number) =>
    textBlock(doc, () => newPage(), text, x, y, maxW, lineH);

  // ── COVER PAGE ─────────────────────────────────────────────────────────────
  header('');
  let y = 32;

  setColor(doc, PDF_COLORS.darkText);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Compliance Packet', margin, y);
  y += 8;

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  setColor(doc, PDF_COLORS.mutedText);
  doc.text(`Prepared for: ${location}`, margin, y); y += 5;
  doc.text(
    `Generated: ${new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}`,
    margin, y,
  ); y += 5;
  doc.text(`Contains ${forms.length} completed form${forms.length !== 1 ? 's' : ''}`, margin, y);
  y += 10;

  // Total estimated fees
  const totalFees = forms.reduce((sum, f) => {
    if (/free/i.test(f.template.fee)) return sum;
    const m = f.template.fee.match(/\$([0-9,]+)/);
    return sum + (m ? parseFloat(m[1].replace(',', '')) : 0);
  }, 0);

  if (totalFees > 0) {
    setFill(doc, PDF_COLORS.bgBlue);
    doc.rect(margin, y, contentW, 12, 'F');
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    setColor(doc, PDF_COLORS.brandBlue);
    doc.text('Estimated total government filing fees (paid separately to agencies):', margin + 3, y + 5);
    doc.text(`$${totalFees.toFixed(0)}+`, pageW - margin - 3, y + 5, { align: 'right' });
    setColor(doc, PDF_COLORS.darkText);
    y += 17;
  }

  // Form index
  setStroke(doc, PDF_COLORS.borderGray);
  doc.line(margin, y, pageW - margin, y); y += 6;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  setColor(doc, PDF_COLORS.darkText);
  doc.text('Forms Included', margin, y); y += 6;

  for (let i = 0; i < forms.length; i++) {
    const { template } = forms[i];
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    setColor(doc, PDF_COLORS.brandBlue);
    doc.text(`${i + 1}.`, margin, y);
    setColor(doc, PDF_COLORS.darkText);
    doc.setFont('helvetica', 'normal');
    const nameLines = doc.splitTextToSize(template.name, contentW - 10) as string[];
    doc.text(nameLines, margin + 7, y);
    setColor(doc, PDF_COLORS.mutedText);
    doc.setFontSize(8);
    doc.text(`Gov. fee: ${template.fee}`, pageW - margin, y, { align: 'right' });
    y += nameLines.length * 5 + 2;
  }

  y += 4;
  setStroke(doc, PDF_COLORS.borderGray);
  doc.line(margin, y, pageW - margin, y); y += 8;

  // Cover disclaimer
  setFill(doc, PDF_COLORS.bgLight);
  doc.rect(margin, y, contentW, 18, 'F');
  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  setColor(doc, PDF_COLORS.faintGray);
  const coverDisclaimer =
    'This compliance packet was generated by RegBot as a preparation aid only. It does not constitute legal advice. ' +
    'Verify all information with official government sources before submitting any application. ' +
    'Consult a licensed attorney or CPA for guidance specific to your situation.';
  const cdLines = doc.splitTextToSize(coverDisclaimer, contentW - 6) as string[];
  doc.text(cdLines, margin + 3, y + 4);

  // ── ONE SECTION PER FORM ───────────────────────────────────────────────────
  for (let fi = 0; fi < forms.length; fi++) {
    const { template, formData } = forms[fi];
    const shortName = template.name.split('(')[0].trim();

    doc.addPage();
    header(`Form ${fi + 1} of ${forms.length}: ${shortName}`, `Fee: ${template.fee}`);
    y = 28;

    // Form title + description
    setColor(doc, PDF_COLORS.darkText);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    const titleLines = doc.splitTextToSize(template.name, contentW) as string[];
    doc.text(titleLines, margin, y);
    y += titleLines.length * 7 + 2;

    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    setColor(doc, PDF_COLORS.mutedText);
    y = tb(template.description, margin, y, contentW, 4.5);
    y += 6;

    setStroke(doc, PDF_COLORS.borderGray);
    doc.line(margin, y, pageW - margin, y); y += 7;

    // Answers
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    setColor(doc, PDF_COLORS.darkText);
    doc.text('Your Answers', margin, y); y += 6;

    for (const field of template.fields) {
      if (y > 265) y = newPage(`Form ${fi + 1} — ${shortName} (continued)`);
      const value = formData[field.id] || '(not provided)';

      // Field label
      doc.setFontSize(8);
      doc.setFont('helvetica', 'bold');
      setColor(doc, PDF_COLORS.labelText);
      doc.text(`${field.label}:`, margin, y); y += 4.5;

      // Official form field reference (e.g. "SS-4 Line 1: Legal name of entity")
      if (field.officialFieldName) {
        doc.setFontSize(6.5);
        doc.setFont('helvetica', 'italic');
        setColor(doc, PDF_COLORS.faintGray);
        doc.text(`↗ ${field.officialFieldName}`, margin + 4, y); y += 3.5;
      }

      // Answer value
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      setColor(doc, PDF_COLORS.mutedText);
      y = tb(value, margin + 4, y, contentW - 4, 4.5);
      y += 3;
    }

    y += 3;
    setStroke(doc, PDF_COLORS.borderGray);
    doc.line(margin, y, pageW - margin, y); y += 6;

    // Required documents
    if (y > 240) y = newPage(`Form ${fi + 1} — Required Documents`);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    setColor(doc, PDF_COLORS.darkText);
    doc.text('Documents You Will Need', margin, y); y += 5;
    for (const reqDoc of template.requiredDocs) {
      if (y > 265) y = newPage(`Form ${fi + 1} — Required Documents (continued)`);
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      setColor(doc, PDF_COLORS.mutedText);
      y = tb(`• ${reqDoc}`, margin, y, contentW - 2, 4.5);
      y += 1;
    }

    y += 4;
    setStroke(doc, PDF_COLORS.borderGray);
    doc.line(margin, y, pageW - margin, y); y += 6;

    // Submission instructions
    if (y > 240) y = newPage(`Form ${fi + 1} — Submission Instructions`);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    setColor(doc, PDF_COLORS.darkText);
    doc.text('How to Submit', margin, y); y += 5;
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    setColor(doc, PDF_COLORS.mutedText);
    y = tb(template.submitInstructions, margin, y, contentW, 4.5); y += 3;
    setColor(doc, PDF_COLORS.brandBlue);
    y = tb(`Official portal: ${template.submitUrl}`, margin, y, contentW, 4.5);
  }

  // ── SUBMISSION ACTION CHECKLIST ────────────────────────────────────────────
  doc.addPage();
  header('Submission Action Checklist');
  y = 28;

  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  setColor(doc, PDF_COLORS.darkText);
  doc.text('What to Do Next', margin, y); y += 5;
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  setColor(doc, PDF_COLORS.mutedText);
  doc.text(`Complete each step below for ${location}`, margin, y); y += 8;

  for (let si = 0; si < forms.length; si++) {
    const { template } = forms[si];
    if (y > 240) y = newPage('Submission Action Checklist (continued)');

    setFill(doc, PDF_COLORS.bgBlue);
    doc.rect(margin, y, contentW, 8, 'F');
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    setColor(doc, PDF_COLORS.brandBlue);
    doc.text(`Step ${si + 1}: ${template.name.split('(')[0].trim()}`, margin + 2, y + 5.5);
    y += 11;

    const steps = [
      `Gather required documents (listed in Form ${si + 1} section above).`,
      `Complete the official application on the agency portal or in person.`,
      `Submit with payment: ${/free/i.test(template.fee) ? 'No fee — this application is free.' : `${template.fee} (government fee — paid to the agency, NOT RegBot).`}`,
      `Keep a copy of your confirmation number or receipt for your records.`,
    ];

    for (const step of steps) {
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      setColor(doc, PDF_COLORS.labelText);
      doc.text('[ ]', margin, y);
      y = tb(step, margin + 7, y, contentW - 7, 4.5);
      y += 1;
    }
    y += 4;
  }

  // Final disclaimer
  if (y > 250) y = newPage('Disclaimer');
  y += 4;
  setFill(doc, PDF_COLORS.bgLight);
  doc.rect(margin, y, contentW, 20, 'F');
  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  setColor(doc, PDF_COLORS.faintGray);
  const finalDisclaimer =
    'RegBot is an AI-powered preparation tool. This packet does not constitute legal advice, and the information ' +
    'provided may not reflect the most current requirements for your jurisdiction. Always verify requirements ' +
    'directly with the relevant government agencies and consult a licensed attorney or accountant before submitting.';
  const fdLines = doc.splitTextToSize(finalDisclaimer, contentW - 6) as string[];
  doc.text(fdLines, margin + 3, y + 4);

  addPageNumbers(doc, pageW, margin, `RegBot Compliance Packet — ${location}`);
  doc.save('regbot-compliance-packet.pdf');
}
