import type { FormTemplate } from './formTemplates';
import {
  PDF_COLORS, setFill, setColor, setStroke,
  renderPageHeader, textBlock, addPageNumbers,
} from './pdf';

export async function generateFormPdf(
  template: FormTemplate,
  formData: Record<string, string>,
  location: string,
): Promise<void> {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'letter' });

  const margin   = 20;
  const pageW    = doc.internal.pageSize.getWidth();
  const contentW = pageW - margin * 2;

  const brand = 'RegBot — Compliance Co-Pilot';
  const right = `Prepared for: ${location}`;

  const newPage = () => {
    doc.addPage();
    renderPageHeader(doc, pageW, margin, brand, right);
    return 28;
  };

  // Shorthand for the text-block helper with this doc's context
  const tb = (text: string, x: number, y: number, maxW: number, lineH?: number) =>
    textBlock(doc, newPage, text, x, y, maxW, lineH);

  // ── Header ─────────────────────────────────────────────────────────────────
  renderPageHeader(doc, pageW, margin, brand, right);
  let y = 28;

  // ── Title + meta ───────────────────────────────────────────────────────────
  setColor(doc, PDF_COLORS.darkText);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  const titleLines = doc.splitTextToSize(template.name, contentW) as string[];
  doc.text(titleLines, margin, y);
  y += titleLines.length * 8 + 2;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  setColor(doc, PDF_COLORS.mutedText);
  doc.text(`Government Filing Fee: ${template.fee}`, margin, y); y += 5;
  doc.text('RegBot Completion Service Fee: $5.00 (paid)', margin, y); y += 5;
  const descLines = doc.splitTextToSize(template.description, contentW) as string[];
  doc.text(descLines, margin, y);
  y += descLines.length * 5 + 6;

  setStroke(doc, PDF_COLORS.borderGray);
  doc.line(margin, y, pageW - margin, y);
  y += 8;

  // ── Fields ─────────────────────────────────────────────────────────────────
  doc.setFontSize(10);
  for (const field of template.fields) {
    const value = formData[field.id] || '(not provided)';
    doc.setFont('helvetica', 'bold');
    setColor(doc, PDF_COLORS.darkText);
    doc.text(`${field.label}:`, margin, y);
    y += 5;
    doc.setFont('helvetica', 'normal');
    setColor(doc, PDF_COLORS.mutedText);
    y = tb(value, margin + 4, y, contentW - 5, 5);
    y += 4;
    if (y > 250) y = newPage();
  }

  y += 4;
  setStroke(doc, PDF_COLORS.borderGray);
  doc.line(margin, y, pageW - margin, y);
  y += 8;

  // ── Required documents ─────────────────────────────────────────────────────
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  setColor(doc, PDF_COLORS.darkText);
  doc.text('Required Supporting Documents', margin, y);
  y += 6;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  setColor(doc, PDF_COLORS.mutedText);
  for (const reqDoc of template.requiredDocs) {
    y = tb(`• ${reqDoc}`, margin, y, contentW, 5);
    y += 1;
  }

  y += 6;
  setStroke(doc, PDF_COLORS.borderGray);
  doc.line(margin, y, pageW - margin, y);
  y += 8;

  // ── Submission instructions ────────────────────────────────────────────────
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  setColor(doc, PDF_COLORS.darkText);
  doc.text('Submission Instructions', margin, y);
  y += 6;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  setColor(doc, PDF_COLORS.mutedText);
  y = tb(template.submitInstructions, margin, y, contentW, 5);
  y += 5;
  setColor(doc, PDF_COLORS.brandBlue);
  y = tb(`Online Portal: ${template.submitUrl}`, margin, y, contentW, 5);
  y += 8;

  // ── Disclaimer ─────────────────────────────────────────────────────────────
  if (y > 240) y = newPage();
  setFill(doc, PDF_COLORS.bgLight);
  doc.rect(margin, y, contentW, 16, 'F');
  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  setColor(doc, PDF_COLORS.faintGray);
  const disclaimer =
    'This document was generated by RegBot as a completion aid only. It does not constitute legal advice. ' +
    'Verify all information with official government sources and consult a licensed attorney before submitting.';
  const discLines = doc.splitTextToSize(disclaimer, contentW - 6) as string[];
  doc.text(discLines, margin + 3, y + 4);

  addPageNumbers(
    doc, pageW, margin,
    'RegBot — Not legal advice. Verify requirements with official government sources.',
  );

  doc.save(`${template.name.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_regbot.pdf`);
}
