import InnerPageLayout from "@/components/landing/InnerPageLayout";
import { AlertTriangle, Scale, CheckCircle2 } from "lucide-react";
import Link from "next/link";

const EFFECTIVE_DATE = "April 1, 2025";

export default function DisclaimerPage() {
  return (
    <InnerPageLayout
      title="Disclaimer"
      subtitle={`Effective date: ${EFFECTIVE_DATE}`}
      darkHero
    >
      {/* Primary disclaimer — prominent callout */}
      <div className="rounded-2xl bg-amber-50 border border-amber-200 px-6 py-6 mb-10 flex gap-4">
        <AlertTriangle className="h-5 w-5 text-amber-500 shrink-0 mt-0.5" />
        <div>
          <p className="text-sm font-bold text-slate-900 mb-2">
            RegPulse is an informational tool — not a law firm
          </p>
          <p className="text-sm text-amber-900 leading-relaxed">
            Nothing on this website or generated by the RegPulse service constitutes legal advice,
            legal opinion, attorney-client relationship, or the practice of law. All content is
            provided for general informational and productivity purposes only.
          </p>
        </div>
      </div>

      <div className="prose prose-slate prose-sm max-w-none [&_h2]:text-slate-900 [&_h2]:font-bold [&_h2]:text-lg [&_h2]:mt-10 [&_h2]:mb-3 [&_p]:text-slate-600 [&_p]:leading-relaxed [&_ul]:text-slate-600 [&_ul]:space-y-1.5 [&_li]:leading-relaxed">

        <h2>Accuracy and completeness</h2>
        <p>
          We strive to provide accurate, hyper-local compliance information. However, business
          regulations — including permits, licensing requirements, zoning codes, health codes, and
          tax rules — vary significantly between jurisdictions and change frequently. RegPulse
          cannot guarantee that all information is current, complete, or applicable to your
          specific situation.
        </p>
        <p>
          Always verify requirements directly with the relevant government agency (city hall,
          county clerk, state licensing board, health department, etc.) before submitting any
          application, paying any fee, or making a compliance decision.
        </p>

        <h2>Not a substitute for professional advice</h2>
        <p>
          The information provided by RegPulse does not replace the advice of a licensed attorney,
          certified public accountant, or other qualified professional. For complex or
          high-stakes compliance decisions — business entity formation, liquor licensing, healthcare
          regulation, employment law, tax strategy — we strongly recommend consulting qualified
          professionals in your jurisdiction.
        </p>

        <h2>AI-generated content</h2>
        <p>
          RegPulse uses artificial intelligence to generate compliance guidance. AI systems can
          make mistakes, produce outdated information, or misunderstand the specific nuances of
          your situation. All AI-generated content should be treated as a starting point for
          your own research, not as authoritative legal or regulatory guidance.
        </p>
        <p>
          We include source references (the relevant law, ordinance, or regulation) wherever
          possible so you can verify information independently. We actively flag when information
          is uncertain and when professional consultation is advisable.
        </p>

        <h2>Government form completion</h2>
        <p>
          RegPulse&rsquo;s AI Form Filler prepares form applications based on information you provide.
          You are solely responsible for:
        </p>
        <ul>
          <li>Verifying that all information entered into government forms is accurate and complete.</li>
          <li>Submitting completed forms to the correct government agency.</li>
          <li>Paying any required government filing fees directly to the issuing agency.</li>
          <li>Ensuring that forms are submitted before applicable deadlines.</li>
          <li>Confirming that the form version used is current — forms change periodically.</li>
        </ul>
        <p>
          RegPulse is not responsible for application rejections, late fees, penalties, or other
          consequences arising from errors in or improper submission of government forms.
        </p>

        <h2>Limitation of liability</h2>
        <p>
          To the fullest extent permitted by applicable law, RegPulse and its owners, employees,
          and agents shall not be liable for any damages — direct, indirect, incidental, punitive,
          or consequential — arising from your reliance on information provided by the Service. See
          our{" "}
          <Link href="/terms" className="text-blue-600 hover:underline">
            Terms of Service
          </Link>{" "}
          for the full limitation of liability provisions.
        </p>

        <h2>External links</h2>
        <p>
          RegPulse may link to external government websites, agency portals, and third-party
          resources. We do not control these sites and are not responsible for their content,
          accuracy, or availability. Links are provided for convenience only and do not constitute
          endorsement.
        </p>

        <h2>Jurisdictional limitations</h2>
        <p>
          RegPulse is designed for use in the United States. Information provided is specific
          to US federal, state, and local regulations. We do not provide guidance on regulations
          in other countries. Even within the US, our coverage varies — we may have more detailed
          information for some jurisdictions than others.
        </p>

      </div>

      {/* What we do well — positive close */}
      <div className="mt-12 rounded-2xl border border-slate-200 bg-slate-50 px-6 py-6">
        <div className="flex items-center gap-2 mb-4">
          <Scale className="h-4 w-4 text-blue-600" />
          <h2 className="text-sm font-bold text-slate-900">What we do stand behind</h2>
        </div>
        <ul className="space-y-2.5">
          {[
            "We cite the specific law, ordinance, or regulation behind every answer so you can verify it.",
            "We flag uncertainty explicitly — if we're not sure, we say so.",
            "We always tell you when a situation requires a licensed attorney.",
            "We do not fabricate citations or government portal URLs.",
            "We improve accuracy continuously based on user feedback and regulatory monitoring.",
          ].map((item) => (
            <li key={item} className="flex items-start gap-2.5 text-sm text-slate-600">
              <CheckCircle2 className="h-4 w-4 text-blue-500 shrink-0 mt-0.5" />
              {item}
            </li>
          ))}
        </ul>
      </div>
    </InnerPageLayout>
  );
}
